config/routes.rb
CeBbs::Application.routes.draw do
  resources :tables

end

app/models/table.rb
class Table < ActiveRecord::Base
  attr_accessible :mess, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render json: @table, status: :created, location: @table }
      else
        format.html { render action: "new" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CeBbs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mess %><br />
    <%= f.text_area :mess %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<html>
  <head>
    <title>メッセージボード</title>
  <body>
    <h1>メッセージの編集</h1>
    <%= render 'form' %>

    <%= link_to '詳細', @table %> |
    <%= link_to '戻る', tables_path %>
  </body>
</html>

app/views/tables/index.html.erb
<html>
  <head>
    <title>メッセージボード</title>
  <body>

    <h1>メッセージボード</h1>

    <hr>

    <table>
      <tr>
        <th>名前</th>
        <th>メッセージ</th>
        <th>修正時間</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @tables.each do |table| %>
      <tr>
        <td><%= table.name %></td>
        <td><%= table.mess %></td>
        <td><%= table.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td><%= link_to '詳細', table %></td>
        <td><%= link_to '編集', edit_table_path(table) %></td>
        <td><%= link_to '削除', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />

    <hr>

    <%= link_to '新規メッセージ', new_table_path %>
  </body>
</html>

app/views/tables/new.html.erb
<html>
  <head>
    <title>メッセージボード</title>
  <body>
    <h1>新規メッセージ</h1>

    <%= render 'form' %>

    <%= link_to '戻る', tables_path %>
  </body>
</html>

app/views/tables/show.html.erb
<html>
  <head>
    <title>メッセージボード</title>
  <body>
    <p id="notice"><%= notice %></p>

    <p>
      <b>名前:</b>
      <%= @table.name %>
    </p>

    <p>
      <b>メッセージ:</b>
      <%= @table.mess %>
    </p>


    <%= link_to '編集', edit_table_path(@table) %> |
    <%= link_to '戻る', tables_path %>
  </body>
</html>